name: Playwright Summary
description: "Formats Playwright test results for better readability"

runs:
  using: "composite"

  steps:
    - name: Format test results
      # Reads the test report file and appends its content to GitHub job summary.
      run: |
        npm install
        npm run test
      shell: bash
