# name: Cache Dependencies for Playwright Tests

# on: push

# jobs:
#   setup:
#     name: cache
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Setup NodeJS
#         uses: actions/setup-node@v4
#         with:
#           node-version: lts/*
#           cache: npm # Enables automatic caching for npm dependencies.

#       - name: Restore npm cache # Restores previously cached npm dependencies.
#         uses: actions/cache@v4
#         with:
#           path: ~/.npm # Specifies the directory to cache (npm's global package storage).
#           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#           # Generates a unique cache key based on OS and package-lock.json hash.
#           restore-keys: |
#             ${{ runner.os }}-node-  # Fallback key if an exact match isn't found.

#       - name: Install dependencies
#         run: npm ci

#       - name: Install Playwright Browsers
#         run: npx playwright install --with-deps

#       - name: Run Playwright tests
#         run: npx playwright test

#   tests:
#       name: tests
#       runs-on: ubuntu-latest

#       steps:
#         - name: Checkout repository
#           uses: actions/checkout@v4

#         - name: Setup NodeJS  # Step 2: Sets up Node.js to run the Playwright tests.
#           uses: actions/setup-node@v4
#           with:
#             node-version: lts/*  # Uses the latest Long-Term Support (LTS) version of Node.js.

#         - name: Install dependencies  # Step 3: Installs project dependencies.
#           run: npm ci  # `npm ci` ensures a clean install based on package-lock.json.

#         - name: Install Playwright Browsers  # Step 4: Installs necessary browsers for Playwright.
#           run: npx playwright install --with-deps  # Includes dependencies required for the browsers.

#         - name: Run Playwright tests  # Step 5: Executes the Playwright tests.
#           run: npx playwright test  # Runs all tests defined in the Playwright test suite.
